vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
        
    mappings:
       attachments:
           uri_prefix: /attachments
           upload_destination: '%kernel.project_dir%/assets/images/attachments'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer